# Syntax highlighting
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Webwings
tagline:             
url:                 https://webwings.cz
baseurl:             /

sass:
  sass_dir:          _sass
  style:            compressed
  
exclude:
  - Gemfile
  - Gemfile.lock
  - nbproject